<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Pragma" content="no-cache" />
<title>Note</title>
<link href="<?php echo APP?>/bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css" />
<link href="<?php echo APP?>/bootstrap/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" />
<script src="<?php echo APP?>/bootstrap/js/jquery.js"></script>
<script src="<?php echo APP?>/bootstrap/js/bootstrap.js"></script>
</head>
<body>

<?php echo $this->layout()->header;?>
<br /><br /><br />
<div class="container-fluid">
<div class="row-fluid">
 <div class="span2 hero-unit">
<?php echo $this->layout()->helper;?>
 </div>
 
 <div class="span7 hero-unit">

<?php echo $this->layout()->content;?>
 
 </div>
 
 </div>
 </div>



<?php echo $this->layout()->footer;?>

</body>
</html>