<div class="navbar navbar-fixed-top form-inline">
<div class="navbar-inner">
<div class="container"><div><a class="brand" href="<?php echo APP;?>">迷你小便笺</a></div>
<ul class="nav">

<li><a href="<?php echo APP . 'index/demo'?>">Welcome</a></li><li class="divider-vertical"></li>

<li><a href="<?php echo APP . 'index/record'?>">新的记录</a></li><li class="divider-vertical"></li>

<li><a href="<?php echo APP . 'index/list'?>">阅读记录</a></li><li class="divider-vertical"></li>

<li><a href="<?php echo APP . 'index/service'?>">服务页</a></li><li class="divider-vertical"></li>

<li><a href="<?php echo APP . 'index/client'?>">客户页</a></li><li class="divider-vertical"></li>
</ul>
</div>
</div>
</div>