
<form action="" method="post">
<div class="alert alert-success">
<h1>Get a new account</h1><br />
<a class="btn btn-large btn-success offset5">Sign Up</a>
<h4>Note 可以帮助你加密储存你的重要信息</h4>
</div>

<table class="table">

<tr>

<td>账户 </td><td><input class="input-xlarge" type="text" name="username" /></td>

</tr>
<tr>

<td>口令 </td><td><input class="input-xlarge" type="text" name="userpass" /></td>

</tr>

<tr>
<td></td><td><button class="btn btn-info" type="submit">Sign In</button></td>
</tr>

<tr>
<td></td><td><a href="">Forget Password ?</a> - <a class="" href="">SignUp</a></td>
</tr>
</table>
</form>